name: car_studio
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_offline: ^3.0.0
  flutter_overlay_loader: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  flutter_swiper_null_safety: ^1.0.2
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  get_it: ^7.6.2
  google_maps_flutter: ^2.5.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  jwt_decode: ^0.3.1
  latlong2: ^0.9.0
  loading_indicator: ^3.1.0
  page_transition: ^2.0.9
  path_provider: ^2.1.1
  pinput: ^3.0.1
  secure_shared_preferences: ^0.0.4
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supercharged: ^2.1.1
  url_launcher: ^6.1.14
  avatar_glow: ^3.0.1
  card_swiper: ^3.0.1


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/studioicon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/en.json
    - assets/translations/ar.json
  # fonts:
  # - family: Lemonada
  #   fonts:
  #     - asset: assets/fonts/Lemonada-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Lemonada-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Lemonada-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Lemonada-Regular.ttf
  #       weight: 400
  #     - asset: assets/fonts/Lemonada-Light.ttf
  # weight: 300